server:
  port: 8080

spring:
  application:
    name: travel-agency-command-side

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
    open-in-view: false
    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}

  kafka:
    bootstrap-servers: kafka:9092
    properties:
      schema.registry.url: http://schema-registry:8200

kafka:
  topics:
    bookings:
      name: travel.bookings
      partitions: 3
      replicas: 1
  outbox:
    poll-interval: 1000
    batch-size: 50
    max-retries: 5


management:
  endpoints:
    web:
      exposure:
        include=health: