server:
  port: ${SERVER_PORT:8080}`

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:travel-agency-command-side}

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 2000
      keepalive-time: 30000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
    open-in-view: false

  kafka:
    bootstrap-servers: kafka:9092
    properties:
      schema.registry.url: http://schema-registry:8200

kafka:
  topics:
    bookings:
      name: travel.bookings
      partitions: 3
      replicas: 1
  outbox:
    poll-interval: 1000
    batch-size: 50
    max-retries: 5


management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      show-details: when_authorized